create database profile2;
use profile2;
create table donors(email varchar(100) primary key,name varchar(30),mobile varchar(12), address varchar(100),city varchar(15),afrom varchar(50),ato varchar(50),gender varchar(15),proof varchar(20),file varchar(100));
select * from donors;
select distinct city from donors;
delete from donors;
drop table donors;
set sql_safe_updates=0;
create table users(txtemail varchar(100) primary key,txtpass varchar(30),txtsel varchar(10));
alter table users add(dos date);
alter table users add(status varchar(1));
select * from users;
delete from needy where email='lavinaguglani456@gmail.com';
delete from users;
update users set status=0 where txtsel='Donor';
update users set status=1 where txtsel='Donor';
create table medsavailable(srno int auto_increment primary key ,email varchar(100),med varchar(100),expdate date,packing varchar(20),qty int );
select * from medsavailable;
select * from medsavailable where email = 'Aarush2218k@gmail.com';
delete from medsavailable where expdate='2024-07-06'; 
delete from medsavailable;
drop table medsavailable;
create table needy(email varchar(100) primary key,name varchar(20),mobile varchar(12),dob date,gender varchar(15),city varchar(30),address varchar(50),picname varchar(100));
select * from needy;
delete from needy;
select * from users where txtemail='aarush@gmail.com' and txtpass='AARUSH@123';
select donors.email,donors.name,donors.mobile,donors.address,donors.city,donors.afrom,donors.ato,donors.gender,medsavailable.med from donors inner join medsavailable on donors.email=medsavailable.email where medsavailable.med='Dolo 650' and donors.city='Bathinda';